from funcoes import*

limpar()

print("C", end="", flush=True)
aguarde(0.3)
print("o", end="", flush=True)
aguarde(0.3)
print("d", end="", flush=True)
aguarde(0.3)
print("e", end="", flush=True)
aguarde(0.3)
print("m", end="", flush=True)
aguarde(0.3)
print("a", end="", flush=True)
aguarde(0.3)
print("s", end="", flush=True)
aguarde(0.3)
print("t", end="", flush=True)
aguarde(0.3)
print("e", end="", flush=True)
aguarde(0.3)
print("r", end="", flush=True)
aguarde(0.3)