<?php

$filmes = [
  novo_filme("The Godfather","img/godf.jpg","img/godfatherbanner.webp","<p>Lorem, ipsum <b>dolor sit amet</b> consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p>"),
  novo_filme("Wolf of Wall Street","img/wolfwallstreet.jpg","img/wolfbanner.jpg","<p>Lorem, ipsum <b>dolor sit amet</b> consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p>"),
  novo_filme("Pulp Fiction","img/pulp.jpg","img/pulpbanner.jpg","<p>Lorem, ipsum <b>dolor sit amet</b> consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p>"),
  novo_filme("Tropa de Elite","img/tropa.jpg","img/tropabanner.webp","<p>Lorem, ipsum <b>dolor sit amet</b> consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p>"),
  novo_filme("GoodFellas","img/goodfellas.jpg","img/goodfellasbanner.jpg","<p>Lorem, ipsum <b>dolor sit amet</b> consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p>"),
  novo_filme("The Godfather 2","img/godf2.jpg","img/godfatherbanner2.webp","<p>Lorem, ipsum <b>dolor sit amet</b> consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p><p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!</p>"),
];


