<?php

$servicos = [
  novo_servico("Serviço 1","img/sv1.jpeg","lorem ipsum paosmd poas mda poda"),
  novo_servico("Serviço 2","img/sv2.jpeg","lorem ipsum paosmd poas mda poda"),
  novo_servico("Serviço 3","img/sv3.jpg","lorem ipsum paosmd poas mda poda"),
  novo_servico("Serviço 4","img/sv4.jpg","lorem ipsum paosmd poas mda poda")
];

$contactos = [
  "morada" => "Loremipsum",
  "telefone" => "+351 222 333 444",
  "email" => "lirem@email.com"
];

$produtos = [
  novo_produto("Produto 1","img/p1.jpg","<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum</p>"),
  novo_produto("Produto 2","img/p2.webp","<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum</p>"),
  novo_produto("Produto 3","img/p3.jpg","<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum</p>"),
  novo_produto("Produto 4","imgp1.jpg","<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum</p>"),
  novo_produto("Produto 5","imgp1.jpg","<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum...Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia, sequi! Numquam a dicta ut, reprehenderit deleniti id eum, molestiae qui dolore voluptatum</p>")

];





?>