<?php

require_once "classes/Viagem.php";
require_once "classes/Slide.php";

$viagens = [
    new Viagem("Lisboa", "img/lisboa.jpg", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!"),
    new Viagem("Porto", "img/porto.webp", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!"),
    new Viagem("Braga", "img/braga.png", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!"),
    new Viagem("Bragança", "img/braganca.png", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!"),
    new Viagem("Serra da Estrela", "img/serra.jpg", "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis, ducimus dolores? Mollitia neque quos fuga rerum aut corrupti nesciunt. Quis rerum excepturi nemo suscipit mollitia non vitae asperiores fugit dolorem!"),
];

$slides = [
    new Slide("img/paisagem_1.avif", "Título 1", "Sou o texto 1"),
    new Slide("img/paisagem_2.avif", "Título 2", "Sou o texto 2"),
    new Slide("img/paisagem_3.avif", "Título 3", "Sou o texto 3"),
    new Slide("img/paisagem_4.avif", "Título 4", "Sou o texto 4"),
    new Slide("img/paisagem_5.avif", "Título 5", "Sou o texto 5"),
];


?>

