from funcoes import*

limpar()

print("C")
aguarde(0.3)
print(" o")
aguarde(0.3)
print("   d")
aguarde(0.3)
print("     e")
aguarde(0.3)
print("       m")
aguarde(0.3)
print("         a")
aguarde(0.3)
print("           s")
aguarde(0.3)
print("             t")
aguarde(0.3)
print("               e")
aguarde(0.3)
print("                 r")
aguarde(1)
limpar()
print("Outra versão")
aguarde(1)
limpar()
print(" " * 0 + "C")
aguarde(0.3)
print(" " * 2 + "o")
aguarde(0.3)
print(" " * 4 + "d")
aguarde(0.3)
print(" " * 6 + "e")
aguarde(0.3)
print(" " * 8 + "m")
aguarde(0.3)
print(" " * 10 + "a")
aguarde(0.3)
print(" " * 12 + "s")
aguarde(0.3)
print(" " * 14 + "t")
aguarde(0.3)
print(" " * 16 + "e")
aguarde(0.3)
print(" " * 18 + "r")
aguarde(0.3)